services:
  kafka:
    image: apache/kafka:4.3.1
    container_name: kafka
    hostname: kafka

    ports:
      - "${KAFKA_EXTERNAL_PORT}:9092"

    environment:
      CLUSTER_ID: "MkU3OEVBNTcwNTJENDM2Qk"

      KAFKA_NODE_ID: 1
      KAFKA_PROCESS_ROLES: "broker,controller"

      KAFKA_LISTENERS: "PLAINTEXT://:9092,INTERNAL://:29092,CONTROLLER://:9093"
      KAFKA_ADVERTISED_LISTENERS: "PLAINTEXT://localhost:${KAFKA_EXTERNAL_PORT},INTERNAL://kafka:29092"

      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: "PLAINTEXT:PLAINTEXT,INTERNAL:PLAINTEXT,CONTROLLER:PLAINTEXT"

      KAFKA_INTER_BROKER_LISTENER_NAME: "INTERNAL"
      KAFKA_CONTROLLER_LISTENER_NAMES: "CONTROLLER"
      KAFKA_CONTROLLER_QUORUM_VOTERS: "1@kafka:9093"

      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1

    volumes:
      - kafka-data:/var/lib/kafka/data

  kafbat-ui:
    image: ghcr.io/kafbat/kafka-ui:v1.3.0
    container_name: kafbat-ui

    depends_on:
      - kafka

    ports:
      - "${KAFBAT_PORT}:8080"

    environment:
      DYNAMIC_CONFIG_ENABLED: "true"

      KAFKA_CLUSTERS_0_NAME: local
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: kafka:29092

  postgres:
    image: postgres:17
    container_name: postgres

    ports:
      - "${POSTGRES_PORT}:5432"

    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}

    volumes:
      - postgres-data:/var/lib/postgresql/data
  
  ollama:
    image: ollama/ollama:latest
    container_name: ollama

    ports:
      - "11434:11434"

    volumes:
      - ollama-data:/root/.ollama

  ollama-init:
    image: ollama/ollama:latest
    depends_on:
      - ollama
    environment:
      OLLAMA_HOST: http://ollama:11434
      OLLAMA_MODEL: qwen3:8b
    volumes:
      - ./docker/ollama/init-model.sh:/init-model.sh:ro
    entrypoint: 
      - /bin/sh
      - /init-model.sh

volumes:
  kafka-data:
  postgres-data:
  ollama-data: